### ISSUE TITLE
这个index.html 只有放在根目录下好使 我要是想放在build目录怎么配置啊

### ISSUE THREAD

**Issue by jindada** [fengnovo/diary#1]

**Comment by jindada** [comment]
diary/react/20161021/webpack-dev-server-proxy-test/ 这个项目

**Comment by fengnovo** [comment]
你要配置啥？webpack-dev-server就是开发时代码热加载和代理转发请求的，你把index.html的build里面，那你这都是编译打包阶段了

**Comment by fengnovo** [comment]
明白你意思了，参考请参考https://github.com/fengnovo/diary/tree/master/react/20161129
要'html-webpack-plugin'，然后相类似下面的设置
plugins: [
    new htmlWebpackPlugin({
      template: __dirname + '/build/build-html/index.html',
      hash: true
    })
  ],
