### ISSUE TITLE
您好，安装您的配置，我设置了我的webpack 1，但是在本地代理后，请求不到地址，报404的错误

### ISSUE THREAD

**Issue by AnhuiWdan** [fengnovo/diary#2]
devServer: {
    istoryApiFallback: true,
    hot: true,
    inline: true,
    stats: {colors: true},
    proxy: {
      '/api/*': {
        target: 'http://localhost/index.php/Home/Index',
        secure: false,
        changeOrigin: true
      }
    }
  },

这个是我的webpack配置，用的是web pack1，

<script>
     
      const url = '/api/ceshi';
      $.get(url,(data) => {
        console.log(data);
      })
    </script>
这个是我请求的接口信息，

然后在浏览器上 GET http://localhost:8080/api/ceshi 404 (Not Found)；
请问大神是哪里的问题呢，我后端用php，也设置了header。
麻烦大神了，谢谢！

**Comment by fengnovo** [comment]
请问你是按我哪个配置设置的webpack？
target: 'http://localhost/index.php/Home/Index',可能你这里有错，这样访问http://localhost:8080/api/ceshi 其实是代理到http://localhost/index.php/Home/Index/ceshi的

**Comment by fengnovo** [comment]
@AnhuiWdan

**Comment by AnhuiWdan** [comment]
https://github.com/fengnovo/diary/tree/master/react/20161021/webpack-dev-server-proxy-test
是这个网址里面的配置。
按照你说的，那我要怎么改呢

**Comment by fengnovo** [comment]
@AnhuiWdan 比方说

> devServer: {
> 		historyApiFallback: true,
>       	hot: true,
> 		inline: true,
> 		stats: { colors: true },
> 		proxy: {
> 	        '/list': {
> 	          target: 'http://10.2.130.20:9000',
> 	          pathRewrite: {'^/column' : '/column'},
> 	          changeOrigin: true
> 	        }
> 	     }
> 	},

当我fetch('/list/column')时在浏览器访问http://localhost:3000/list/column 时实际取
http://10.2.130.20:9000/column 数据

> /list/column  --> http://10.2.130.20:9000/column

**Comment by AnhuiWdan** [comment]
你写的这个，我不太能看得懂哎，有点像是访问http://localhost:3000/list/column相当于访问http://10.2.130.20:9000/column，是这个意思吗

**Comment by AnhuiWdan** [comment]
嗯，又看了一下，是要在/list/column前面加上我的localhost:8080吗

**Comment by fengnovo** [comment]
http://localhost/index.php/Home/Index  你这个路径能在浏览器里访问到数据吗？
你最终是要访问 http://localhost/index.php/Home/Index/api/ceshi 
还是 http://localhost/index.php/Home/Index/ceshi ？

**Comment by AnhuiWdan** [comment]
这个是我本地的服务器，可以取到值，我要访问的是 http://localhost/index.php/Home/Index/ceshi 这个里面的数据

**Comment by fengnovo** [comment]
打比方，你要访问  http://localhost/index.php/Home/Index/ceshi  即类似 http://10.2.130.20:9000/column 那么，就要这样
>  proxy: {
> 	        //	/ceshi -->  http://localhost/index.php/Home/Index/ceshi
> 	        '/ceshi': {
> 	        	target: 'http://localhost/index.php/Home/Index',
> 	        	pathRewrite: {'^/': '/'},
> 	        	changeOrigin: true
> 	        }
> 	     }

**Comment by AnhuiWdan** [comment]
嗯嗯，我在jquery里面是要写‘/ceshi/ceshi’,还是‘/ceshi就可以’，还有那个pathRewrite里面要写^/ceshi : / 吗

**Comment by fengnovo** [comment]
上面你这么写会比较乱，建议你按下面改你之前的代码，这样代理才有效
>  devServer: {
> historyApiFallback: true,
> hot: true,
> inline: true,
> stats: {colors: true},
> proxy: {
> '/ceshi': {
> target: 'http://localhost/index.php/Home/Index',
> secure: false,
> changeOrigin: true
> }
> }
> },
然后，
`<script> const url = '/ceshi'; $.get(url,(data) => { console.log(data); }) </script>`
----------------------------------------------------------------------------------------------
**后话**
这个定义接口是应该最好有个统一的打头，意思就是都用一个类似api的字打头
http://localhost/index.php/Home/Index/api/xxxid
http://localhost/index.php/Home/Index/api/ceshi
请求时
api/xxxid
api/ceshi 
...

这样前端才好用一个统一的

> '/api/*': {
> target: 'http://localhost/index.php/Home/Index',
> secure: false,
> changeOrigin: true
> }
这样就不用写很多个proxy
我那个例子就是因为没有统一一致的关键字，要写很多个proxy关键字匹配

**Comment by AnhuiWdan** [comment]
我按照你的写法，重新写了我的devServer和get请求，但是还是请求不到。报的依然是404

Request URL:http://localhost:8080/ceshi
Request Method:GET
Status Code:404 Not Found
Remote Address:[::1]:8080
Referrer Policy:no-referrer-when-downgrade

这个是请求headers里的General内容。

**Comment by fengnovo** [comment]
你再仔细理解一下
我要代理访问 https://cnodejs.org/api/v1/topics ，我先把/topics取出来，
> proxy: {
> 	        '/topics': {
> 				target: 'https://cnodejs.org/api/v1',
> 				secure: false,
> 				changeOrigin: true
> 			}
> 	     }
上面target拼接key的名称的/topics就是完整路径 https://cnodejs.org/api/v1/topics

**Comment by AnhuiWdan** [comment]
不好意思，这么久才回复你的信息，你说的这个我用在我的webpack上，但是还是404 的错误，我已经懵逼了，最后在php里写的跨域的header，可以了，很感谢你的指点，我回去升级我的webpack，可能是版本的问题。谢谢你！
