### ISSUE TITLE
上生产环境，proxy怎么改

### ISSUE THREAD

**Issue by scc02** [fengnovo/diary#3]
比如开发环境都用/list代替，上生产环境的时候怎么办？

**Comment by fengnovo** [comment]
如果是部署到服务器，生产环境用Nginx或其他服务器做一样的映射，如果是混合开发，打包原生壳的页面的话要加完整域名  @ShiChenCong

**Comment by scc02** [comment]
``` 
proxy: {
            '/api':{
                target:'https://api.douban.com/',
                pathRewrite: {'^/api' : ''},
                changeOrigin: true,
            }
    }

fetch('/api/v2/book/1220562')
```
上生产之后，用nginx映射api吗，把api映射成https://api.douban.com/
@fengnovo

**Comment by fengnovo** [comment]
具体你可以网上查一下怎么设置Nginx代理，这是我自己云服务器的一个Nginx配置，我把请求用Nginx转发到知乎日报，然后获取知乎日报api数据返回给前端，你参考一下 @ShiChenCong 
    server {
        listen       80;
        server_name  localhost;

        #charset koi8-r;

        #access_log  logs/host.access.log  main;

        location /api/zhihu/ {
            proxy_pass http://news-at.zhihu.com/api/4/;
        }

        location / {
            root   html;
            index  index.html index.htm;
        }

        #error_page  404              /404.html;

        # redirect server error pages to the static page /50x.html
        #
        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   html;
        }

        # proxy the PHP scripts to Apache listening on 127.0.0.1:80
        #
        #location ~ \.php$ {
        #    proxy_pass   http://127.0.0.1;
        #}

        # pass the PHP scripts to FastCGI server listening on 127.0.0.1:9000
        #
        #location ~ \.php$ {
        #    root           html;
        #    fastcgi_pass   127.0.0.1:9000;
        #    fastcgi_index  index.php;
        #    fastcgi_param  SCRIPT_FILENAME  /scripts$fastcgi_script_name;
        #    include        fastcgi_params;
        #}

        # deny access to .htaccess files, if Apache's document root
        # concurs with nginx's one
        #
        #location ~ /\.ht {
        #    deny  all;
        #}
    }
